#!/usr/bin/perl
# This one is a trivial data dumping utility, for looking at what data
# structures Audio::Scan is throwing at us. Distributed under the same
# terms as `arename' itself.  Note, that this is not indented as an
# end-user program. Its usage is simple, though:
#    % perl asdump /path/to/foo.mp3
use warnings;
use strict;
use Data::Dumper;
use Audio::Scan;
$Data::Dumper::Indent = 3;
local $ENV{AUDIO_SCAN_NO_ARTWORK} = 1;
my $dat = Audio::Scan->scan($ARGV[0]);
print Dumper($dat);
