# default installation location:
#   binaries: /usr/local/bin
#   module  : /usr/local/lib/site_perl
prefix="/usr/local"
libpath="lib/site_perl"
install=install

# the place where *I* keep the sources of arename's "website".
# The whole updatewebsite-fu is probably not useful for anybody else.
ikiroot=/home/hawk/src/web/ft/comp
ikisubroot=/home/hawk/src/web/subpages.ft/comp/arename

all:
	@printf 'Makefile targets intended for users:\n'
	@printf '  all            this text\n'
	@printf '  install        install both scripts and the module\n'
	@printf '  install-doc    install all documentation\n'
	@printf '\nAll other targets are not for you. Stay away!\n'

dev-help: all
	@printf '\nMakefile targets intended for developers:\n'
	@printf 'DO NOT USE THESE UNLESS YOU KNOW WHAT YOU ARE DOING!\n'
	@printf '  arename.1      generate manpage\n'
	@printf '  arename.html   generate manpage in html format\n'
	@printf '  doc            generate arename.1 and arename.html\n'
	@printf '  dev-help       this text\n'
	@printf '  clean          clean up working tree\n'
	@printf '  distclean      same as clean, but removes .tars, too\n'
	@printf '  updateweb      update the autogenerated website\n'
	@printf '  removeweb      clean up the website'\''s target directory\n'

doc: arename.1 arename.html

arename.1: arename.pl
	pod2man  ./arename.pl > arename.1    2>/dev/null

arename.html: arename.pl
	pod2html ./arename.pl > arename.html 2>/dev/null
	@rm -f *.tmp

clean:
	rm -f arename.html arename.1 *.tmp *~

distclean: clean
	rm -f *.tar.gz

install:
	@printf 'Installing arename.pl    to %s\n' "$(prefix)/bin"
	@$(install) -oroot -groot -m0755 -D arename.pl "$(prefix)/bin"
	@printf 'Installing ataglist.pl   to %s\n' "$(prefix)/bin"
	@$(install) -oroot -groot -m0755 -D ataglist.pl "$(prefix)/bin"
	@printf 'Installing ARename.pm    to %s\n' "$(prefix)/$(libpath)/"
	@$(install) -oroot -groot -m0755 -D ARename.pm "$(prefix)/$(libpath)"

install-doc: doc
	@printf 'Installing README        to %s\n' "$(prefix)/share/doc/arename"
	@$(install) -oroot -groot -m0644 -D README "$(prefix)/share/doc/arename"
	@printf 'Installing LICENCE       to %s\n' "$(prefix)/share/doc/arename"
	@$(install) -oroot -groot -m0644 -D LICENCE "$(prefix)/share/doc/arename"
	@printf 'Installing CHANGES       to %s\n' "$(prefix)/share/doc/arename"
	@$(install) -oroot -groot -m0644 -D CHANGES "$(prefix)/share/doc/arename"
	@printf 'Installing arename.1     to %s\n' "$(prefix)/share/man/man1"
	@$(install) -oroot -groot -m0644 -D arename.1 "$(prefix)/share/man/man1/"
	@printf 'Installing arename.html  to %s\n' "$(prefix)/share/doc/arename"
	@$(install) -oroot -groot -m0644 -D arename.html "$(prefix)/share/doc/arename/examples"
	@printf 'Installing arename.hooks to %s\n' "$(prefix)/share/doc/arename/examples"
	@$(install) -oroot -groot -m0644 -D arename.hooks "$(prefix)/share/doc/arename/examples"
	@printf 'Installing _arename      to %s\n' "$(prefix)/share/doc/arename/examples"
	@$(install) -oroot -groot -m0644 -D _arename "$(prefix)/share/doc/arename/examples"

updateweb:
	@printf 'Updating webpages...\n'
	@./updatewebsite.sh "$(ikiroot)" "$(ikisubroot)"
	make distclean

removeweb:
	@printf 'Remove webpages...\n'
	rm -f "$(ikiroot)"/arename.mdwn "$(ikisubroot)"/*

.PHONY: install install-doc distclean clean all doc
