# default installation location:
#   binaries: /usr/local/bin
#   module  : /usr/local/lib/site_perl
prefix="/usr/local"
libpath="lib/site_perl"

# the place where *I* keep the sources of arename's "website".
# The whole updatewebsite-fu is probably not useful for anybody else.
ikiroot=/home/hawk/src/web/ft/comp
ikisubroot=/home/hawk/src/web/subpages.ft/comp/arename

all:
	@printf 'Makefile targets intended for users:\n'
	@printf '  all            this text\n'
	@printf '  arename.1      build the manpage\n'
	@printf '                 (requires pod2man)\n'
	@printf '  arename.html   build the html manual\n'
	@printf '                 (requires pod2html)\n'
	@printf '  doc            calls both manual builders\n'
	@printf '                 mentioned above\n'
	@printf '  install        install both scripts and the module\n'
	@printf '  install-doc    install html and nroff manual\n'
	@printf '  clean          remove the autogenerated files\n'
	@printf '\nAll other targets are not for you. Stay away!\n'

doc: arename.1 arename.html

arename.1: arename.pl
	pod2man  ./arename.pl > arename.1    2>/dev/null

arename.html: arename.pl
	pod2html ./arename.pl > arename.html 2>/dev/null
	@rm -f *.tmp

clean:
	rm -f arename.html arename.1 *.tmp *~

distclean: clean
	rm -f *.tar.gz

install:
	@printf 'Installing arename.pl   to %s\n' "$(prefix)/bin"
	@cp arename.pl   "$(prefix)/bin/"
	@printf 'Installing ataglist.pl  to %s\n' "$(prefix)/bin"
	@cp ataglist.pl  "$(prefix)/bin/"
	@chown root:root "$(prefix)/bin/arename.pl" "$(prefix)/bin/ataglist.pl"
	@chmod 0755      "$(prefix)/bin/arename.pl" "$(prefix)/bin/ataglist.pl"
	@printf 'Installing ARename.pm   to %s\n' "$(prefix)/$(libpath)/"
	@[ ! -d "$(prefix)/$(libpath)" ] && (mkdir -p "$(prefix)/$(libpath)" && chmod 0755 "$(prefix)/$(libpath)" ) || true
	@cp ARename.pm   "$(prefix)/$(libpath)"
	@chmod 0644      "$(prefix)/$(libpath)/ARename.pm"

install-doc: doc
	@printf 'Installing arename.1    to %s\n' "$(prefix)/share/man/man1"
	@cp arename.1    "$(prefix)/share/man/man1/"
	@chown root:root "$(prefix)/share/man/man1/arename.1"
	@chmod 0644      "$(prefix)/share/man/man1/arename.1"
	@printf 'Installing arename.html to %s\n' "$(prefix)/share/doc/arename"
	@mkdir -p        "$(prefix)/share/doc/arename"
	@chmod 0755      "$(prefix)/share/doc/arename"
	@cp arename.html "$(prefix)/share/doc/arename/"
	@chown root:root "$(prefix)/share/doc/arename/arename.html"
	@chmod 0644      "$(prefix)/share/doc/arename/arename.html"

updateweb:
	@printf 'Updating webpages...\n'
	@./updatewebsite.sh "$(ikiroot)" "$(ikisubroot)"
	make distclean

removeweb:
	@printf 'Remove webpages...\n'
	rm -f "$(ikiroot)"/arename.mdwn "$(ikisubroot)"/*

.PHONY: install install-doc distclean clean all doc
